<?php

namespace App\Filament\Support;

class VietnameseLabel
{
    public static function for(string $name): ?string
    {
        $field = (string) str($name)->afterLast('.');

        return match ($field) {
            'account_name' => 'Tên chủ tài khoản',
            'amount' => 'Số tiền',
            'approved_at' => 'Thời gian phê duyệt',
            'assigned_to' => 'Người phụ trách',
            'availability_status' => 'Trạng thái sẵn sàng',
            'balance' => 'Số dư',
            'balance_after' => 'Số dư sau giao dịch',
            'bank_code' => 'Mã ngân hàng',
            'bank_transfer_reference' => 'Mã tham chiếu chuyển khoản',
            'base_distance_km' => 'Số km cơ bản',
            'base_fare' => 'Cước cơ bản',
            'body' => 'Nội dung',
            'booking_type' => 'Loại đặt dịch vụ',
            'boundary' => 'Ranh giới khu vực',
            'brand' => 'Hãng xe',
            'cancellation_reason_code' => 'Lý do hủy',
            'cash_collected' => 'Tiền mặt đã thu',
            'category' => 'Danh mục',
            'cod_limit' => 'Hạn mức COD',
            'color' => 'Màu sắc',
            'comment' => 'Nhận xét',
            'created_at' => 'Thời gian tạo',
            'currency' => 'Tiền tệ',
            'customer_payable' => 'Số tiền khách hàng phải trả',
            'cod_amount' => 'Số tiền COD',
            'goods_type' => 'Loại hàng hóa',
            'payer_type' => 'Người thanh toán',
            'description' => 'Mô tả',
            'direction' => 'Chiều',
            'distance_km' => 'Quãng đường (km)',
            'document_number' => 'Số giấy tờ',
            'document_type' => 'Loại giấy tờ',
            'documents' => 'Giấy tờ',
            'documents_count' => 'Số giấy tờ',
            'driver_gross_earning' => 'Thu nhập gộp của tài xế',
            'driver_net_earning' => 'Thu nhập thực nhận của tài xế',
            'driver_rate' => 'Tỷ lệ tài xế nhận',
            'effective_from' => 'Có hiệu lực từ',
            'effective_to' => 'Có hiệu lực đến',
            'email' => 'Email',
            'evidence' => 'Bằng chứng',
            'evidence_type' => 'Loại bằng chứng',
            'evidences' => 'Bằng chứng',
            'expires_at' => 'Hết hạn lúc',
            'gross_fare' => 'Tổng cước',
            'handled_at' => 'Thời gian xử lý',
            'incident_type' => 'Loại sự cố',
            'is_active' => 'Đang hoạt động',
            'is_default' => 'Mặc định',
            'is_public' => 'Công khai',
            'is_selected' => 'Được chọn',
            'is_verified' => 'Đã xác minh',
            'key' => 'Khóa',
            'last_login_at' => 'Đăng nhập lần cuối',
            'entries' => 'Bút toán sổ cái',
            'max_height_cm' => 'Chiều cao tối đa (cm)',
            'max_length_cm' => 'Chiều dài tối đa (cm)',
            'max_weight_kg' => 'Khối lượng tối đa (kg)',
            'max_width_cm' => 'Chiều rộng tối đa (cm)',
            'message_type' => 'Loại tin nhắn',
            'messages' => 'Tin nhắn',
            'method' => 'Phương thức thanh toán',
            'moderation_status' => 'Trạng thái kiểm duyệt',
            'model' => 'Mẫu xe',
            'name' => 'Tên',
            'original_name' => 'Tên tệp gốc',
            'passenger_capacity' => 'Sức chứa hành khách',
            'payment_method' => 'Phương thức thanh toán',
            'phone' => 'Số điện thoại',
            'phone_verified_at' => 'Thời gian xác minh số điện thoại',
            'plate_number' => 'Biển số xe',
            'platform_fee_debited' => 'Phí nền tảng',
            'price_per_extra_km' => 'Giá mỗi km thêm',
            'priority' => 'Mức ưu tiên',
            'public_id' => 'Mã công khai',
            'distance_meters' => 'Quãng đường (m)',
            'duration_seconds' => 'Thời lượng (giây)',
            'quotes_count' => 'Số báo giá',
            'reason_code' => 'Lý do',
            'requested_at' => 'Thời gian yêu cầu',
            'reserved_withdrawal_amount' => 'Số tiền giữ để rút',
            'resolution_code' => 'Mã xử lý',
            'resolution_note' => 'Ghi chú xử lý',
            'resolved_at' => 'Thời gian xử lý xong',
            'review_reason_code' => 'Lý do xét duyệt',
            'review_status' => 'Trạng thái xét duyệt',
            'reviewed_at' => 'Thời gian xét duyệt',
            'roles' => 'Vai trò',
            'scheduled' => 'Đặt lịch',
            'scheduled_at' => 'Thời gian đặt lịch',
            'score' => 'Điểm đánh giá',
            'search_started_at' => 'Bắt đầu tìm tài xế lúc',
            'service_type' => 'Loại dịch vụ',
            'settled_at' => 'Thời gian quyết toán',
            'settlement_adjustment' => 'Điều chỉnh quyết toán',
            'severity' => 'Mức độ nghiêm trọng',
            'status' => 'Trạng thái',
            'subject' => 'Tiêu đề',
            'submitted_at' => 'Thời gian gửi xét duyệt',
            'tags' => 'Nhãn',
            'transaction_type' => 'Loại giao dịch',
            'unique_key' => 'Mã duy nhất',
            'updated_at' => 'Cập nhật lúc',
            'value' => 'Giá trị',
            'vehicle_type_id' => 'Loại xe',
            'vehicles' => 'Xe',
            'vehicles_count' => 'Số xe',
            'voucher_discount' => 'Giảm giá mã khuyến mãi',
            'voucher_payment_amount' => 'Số tiền thanh toán bằng mã khuyến mãi',
            default => null,
        };
    }

    public static function value(string $name, mixed $state): mixed
    {
        if (! is_string($state)) {
            return $state;
        }

        if ($name === 'roles.name') {
            return match ($state) {
                'ADMIN' => 'Quản trị viên',
                'CUSTOMER' => 'Khách hàng',
                'DRIVER' => 'Tài xế',
                'SUPPORT' => 'Hỗ trợ',
                default => $state,
            };
        }

        if (! in_array((string) str($name)->afterLast('.'), [
            'availability_status',
            'booking_type',
            'category',
            'direction',
            'document_type',
            'evidence_type',
            'incident_type',
            'message_type',
            'method',
            'moderation_status',
            'payer_type',
            'priority',
            'review_status',
            'service_type',
            'severity',
            'status',
            'transaction_type',
        ], true)) {
            return $state;
        }

        return match ($state) {
            'ACTIVE' => 'Đang hoạt động',
            'ADMIN' => 'Quản trị viên',
            'ADVANCE_TO_SENDER' => 'Ứng COD cho người gửi',
            'APPROVED' => 'Đã phê duyệt',
            'CANCELLED' => 'Đã hủy',
            'CASH' => 'Tiền mặt',
            'CLOSED' => 'Đã đóng',
            'COLLECT_FROM_RECIPIENT' => 'Thu COD từ người nhận',
            'COMPLETED' => 'Đã hoàn thành',
            'CRITICAL' => 'Nghiêm trọng',
            'CUSTOMER' => 'Khách hàng',
            'CUSTOMER_PAYMENT' => 'Khách hàng thanh toán',
            'CUSTOMER_PAYMENT_REFUND' => 'Hoàn tiền cho khách hàng',
            'CUSTOMER_TO_DRIVER' => 'Khách hàng đánh giá tài xế',
            'DECLINED' => 'Đã từ chối',
            'DELIVERY' => 'Giao hàng',
            'DELIVERY_FAILED' => 'Giao hàng thất bại',
            'DELIVERED' => 'Đã giao hàng',
            'DRIVER' => 'Tài xế',
            'DRIVER_TO_CUSTOMER' => 'Tài xế đánh giá khách hàng',
            'DRAFT' => 'Bản nháp',
            'DRIVE' => 'Đặt xe',
            'FAILED' => 'Thất bại',
            'FROZEN' => 'Đã khóa',
            'GENERAL' => 'Chung',
            'HIGH' => 'Cao',
            'HIDDEN' => 'Đã ẩn',
            'IDENTITY' => 'Căn cước công dân',
            'IN_REVIEW' => 'Đang xử lý',
            'LOW' => 'Thấp',
            'NORMAL' => 'Bình thường',
            'OFFLINE' => 'Ngoại tuyến',
            'ONLINE' => 'Trực tuyến',
            'OPEN' => 'Đang mở',
            'ORDERER' => 'Người đặt',
            'PENDING' => 'Chờ xử lý',
            'PENDING_REVIEW' => 'Chờ xét duyệt',
            'RECIPIENT' => 'Người nhận',
            'REJECTED' => 'Đã từ chối',
            'RESOLVED' => 'Đã xử lý',
            'SETTLED' => 'Đã quyết toán',
            'SUPPORT' => 'Hỗ trợ',
            'SUSPENDED' => 'Tạm ngưng',
            'URGENT' => 'Khẩn cấp',
            'VERIFIED' => 'Đã xác minh',
            'VISIBLE' => 'Hiển thị',
            'WALLET' => 'Ví',
            default => $state,
        };
    }
}
